---
- name: Common | Add Docker Group
  group: name=docker state=present
  sudo: yes
  tags: common

- name: Common | Add Vagrant user to Docker Group
  user: name=vagrant shell=/bin/bash groups=vagrant,docker append=yes
  sudo: yes
  tags: common

- name: Common | Create Docker volume dirs
  file: path=/srv/docker state=directory
  sudo: yes
  tags: common

