---
# - name: Ruby | Dependencies
#   command: apt-get install git-core curl zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt1-dev libcurl4-openssl-dev python-software-properties
#   sudo: yes
#   tags: ruby  

# - name: Ruby | Dependencies 2
#   command: apt-get install libgdbm-dev libncurses5-dev automake libtool bison libffi-dev
#   sudo: yes
#   tags: ruby  

- name: Ruby | Install Ruby
  apt: pkg=ruby update-cache=yes
  sudo: yes
  tags: ruby

- name: Ruby | Install compass gem
  apt: pkg=ruby-compass update-cache=yes
  #gem: name=compass
  # command: gem install compass
  sudo: yes
  tags: ruby