redis:
  name: redis
  image: redis
  command: redis-server --appendonly yes
  ports:
    - "6379:6379"
  volumes:
    - /srv/docker/redis:/data

postgresql:
  name: postgresql
  image: sameersbn/postgresql:9.4-2
  environment:
    - DB_USER=redmine
    - DB_PASS=skwxhStJ
    - DB_NAME=passanager
  volumes:
    - /srv/docker/postgresql:/var/lib/postgresql
    - /srv/docker/backup:/shareddb
    - /vagrant/backup:/shared

pgstudio:
  image: lukasmartinelli/pgstudio
  links:
    - postgresql:postgresql
  ports:
    - "8181:8080"