---
- name: Install Development Environment
  hosts:  127.0.0.1
  connection: local
  # remote_user: root
  user: vagrant
  sudo: yes

  tasks:
    - name: update apt cache
      apt: update_cache=yes

  roles:
    - common
    #- nginx
    - nodesource.node #ansible-galaxy install nodesource.node
    - ruby
    - golang
    - angstwad.docker_ubuntu #ansible-galaxy install angstwad.docker_ubuntu
    # - docker ## Note there is a bug in ansible docker, switch to use docker compose instead